### ISSUE TITLE
Rename file feature fails

### ISSUE THREAD

**Issue by khode-mx** [Mcpoowl/SFTPModule#8]
I noticed that the file rename feature does not work. The cause lies in the fact that the OldFilename value is changed in the Connection object without a commit. After setting the new file name on the screen, the processing microflow retrieves the connection based on a database retrieve of Account. As a result, the 'old' instance of Connection will be retrieved over association which does not include the latest OldFilename value.

The fix would be to change the SUB_GetCurrentAccount microflow to cast the Account from memory instead of doing a database retrieve each time.

**Comment by Mcpoowl** [comment]
Hi Dennis, thanks for letting me know. Some time ago on a Mendix Meetup, we had a discussion about all the different SFTP modules that are available in the appstore. Our solution was that one module would be the go-to-module and the other ones would die a silent death. Since we needed someone that could take ownership of the module, and the this FTP module is made in my Pink Elephant time, I couldn't just take it with me (ownership and such), so we decided that the Capgemini module would be updated and extended, and that would be the go-to module.

I noticed the module is updated in the appstore, I'm just not sure if the module contains everything this module does. I see you've done a pull-request on that module, so I think you've tried it?

If you want you can issue a pull request here, but I doubt i'll be making a new release for the appstore, for the sake of confusion

**Comment by khode-mx** [comment]
Thanks for the headsup!
